name: Publish to GitHub Pages
on:
  push:
    branches: [ dev ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
  - name: Install oboe
    run: |
      python -m pip install --upgrade pip
      pip install git+https://github.com/kmaasrud/oboe.git
  - name: Generate HTML through oboe
    run: oboe notes/ -d -o ./notes_html/
  - name: Publish
    uses: s0/git-publish-subdir-action@develop
    env:
      REPO: self
      BRANCH: gh-pages
      FOLDER: notes_html
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

