name: Publish to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Clean install dependencies
        run: pip install fire beautifulsoup4 && cd pages && npm ci
      - name: Run deploy script
        run: |
          git config user.name "amead24"
          git config user.email "avmead24@gmail.com"
          python pages/scripts/parse_notes.py
          cd pages && npm run gh-pages-deploy
